repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.8
    hooks:
        # Run the linter.
        # Ignore F (pyflakes) currently
        -   id: ruff-check
            args: [ --fix, --ignore=F ]
            types: [python]
        # Run the formatter.
        -   id: ruff-format
            types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: end-of-file-fixer
        files: ^(examples|src|tests)/
        exclude: ^tests/analysis/data/
    -   id: trailing-whitespace
        files: ^(examples|src|tests)/
        exclude: ^tests/analysis/data/
