// https://syzkaller.appspot.com/bug?id=8ee64ef828f4e3ef333bb56d7f9ab18b057905be
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#ifndef __NR_bpf
#define __NR_bpf 321
#endif

static unsigned long long procid;

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      sleep_ms(10);
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

uint64_t r[1] = {0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  //  perf_event_open arguments: [
  //    attr: ptr[in, perf_event_attr] {
  //      perf_event_attr {
  //        type: perf_event_type = 0x1 (4 bytes)
  //        size: len = 0x80 (4 bytes)
  //        config0: int8 = 0x0 (1 bytes)
  //        config1: int8 = 0x0 (1 bytes)
  //        config2: int8 = 0x0 (1 bytes)
  //        config3: int8 = 0x0 (1 bytes)
  //        config4: const = 0x0 (4 bytes)
  //        sample_freq: int64 = 0x4d31 (8 bytes)
  //        sample_type: perf_sample_type = 0x0 (8 bytes)
  //        read_format: perf_read_format = 0x0 (8 bytes)
  //        disabled: int64 = 0x0 (0 bytes)
  //        inherit: int64 = 0x0 (0 bytes)
  //        pinned: int64 = 0x0 (0 bytes)
  //        exclusive: int64 = 0x0 (0 bytes)
  //        exclude_user: int64 = 0x0 (0 bytes)
  //        exclude_kernel: int64 = 0x0 (0 bytes)
  //        exclude_hv: int64 = 0x0 (0 bytes)
  //        exclude_idle: int64 = 0x0 (0 bytes)
  //        mmap: int64 = 0x0 (0 bytes)
  //        comm: int64 = 0x0 (0 bytes)
  //        freq: int64 = 0x0 (0 bytes)
  //        inherit_stat: int64 = 0x0 (0 bytes)
  //        enable_on_exec: int64 = 0x0 (0 bytes)
  //        task: int64 = 0x0 (0 bytes)
  //        watermark: int64 = 0x0 (0 bytes)
  //        precise_ip: int64 = 0x0 (0 bytes)
  //        mmap_data: int64 = 0x0 (0 bytes)
  //        sample_id_all: int64 = 0x0 (0 bytes)
  //        exclude_host: int64 = 0x0 (0 bytes)
  //        exclude_guest: int64 = 0x0 (0 bytes)
  //        exclude_callchain_kernel: int64 = 0x0 (0 bytes)
  //        exclude_callchain_user: int64 = 0x0 (0 bytes)
  //        mmap2: int64 = 0x0 (0 bytes)
  //        comm_exec: int64 = 0x0 (0 bytes)
  //        use_clockid: int64 = 0x0 (0 bytes)
  //        context_switch: int64 = 0x0 (0 bytes)
  //        write_backward: int64 = 0x0 (0 bytes)
  //        namespaces: int64 = 0x0 (0 bytes)
  //        ksymbol: int64 = 0x0 (0 bytes)
  //        bpf_event: int64 = 0x0 (0 bytes)
  //        aux_output: int64 = 0x0 (0 bytes)
  //        cgroup: int64 = 0x0 (0 bytes)
  //        text_poke: int64 = 0x0 (0 bytes)
  //        build_id: int64 = 0x0 (0 bytes)
  //        inherit_thread: int64 = 0x0 (0 bytes)
  //        remove_on_exec: int64 = 0x0 (0 bytes)
  //        sigtrap: int64 = 0x0 (0 bytes)
  //        __reserved_1: const = 0x0 (8 bytes)
  //        wakeup_events: int32 = 0x0 (4 bytes)
  //        bp_type: perf_bp_type = 0x4 (4 bytes)
  //        bp_config: union perf_bp_config {
  //          perf_config_ext: perf_config_ext {
  //            config1: int64 = 0x8 (8 bytes)
  //            config2: int64 = 0x830d (8 bytes)
  //          }
  //        }
  //        branch_sample_type: perf_branch_sample_type = 0x0 (8 bytes)
  //        sample_regs_user: int64 = 0x2 (8 bytes)
  //        sample_stack_user: int32 = 0xfffffffe (4 bytes)
  //        clockid: clock_type = 0x0 (4 bytes)
  //        sample_regs_intr: int64 = 0x0 (8 bytes)
  //        aux_watermark: int32 = 0x0 (4 bytes)
  //        sample_max_stack: int16 = 0x0 (2 bytes)
  //        __reserved_2: const = 0x0 (2 bytes)
  //        aux_sample_size: int32 = 0x0 (4 bytes)
  //        __reserved_3: const = 0x0 (4 bytes)
  //        sig_data: int64 = 0x0 (8 bytes)
  //      }
  //    }
  //    pid: pid (resource)
  //    cpu: intptr = 0xffffffffffffffff (8 bytes)
  //    group: fd_perf (resource)
  //    flags: perf_flags = 0x0 (8 bytes)
  //  ]
  //  returns fd_perf
  *(uint32_t*)0x2000000003c0 = 1;
  *(uint32_t*)0x2000000003c4 = 0x80;
  *(uint8_t*)0x2000000003c8 = 0;
  *(uint8_t*)0x2000000003c9 = 0;
  *(uint8_t*)0x2000000003ca = 0;
  *(uint8_t*)0x2000000003cb = 0;
  *(uint32_t*)0x2000000003cc = 0;
  *(uint64_t*)0x2000000003d0 = 0x4d31;
  *(uint64_t*)0x2000000003d8 = 0;
  *(uint64_t*)0x2000000003e0 = 0;
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 0, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 1, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 2, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 3, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 4, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 5, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 6, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 7, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 8, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 9, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 10, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 11, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 12, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 13, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 14, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 15, 2);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 17, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 18, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 19, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 20, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 21, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 22, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 23, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 24, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 25, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 26, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 27, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 28, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 29, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 30, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 31, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 32, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 33, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 34, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 35, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 36, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 37, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000003e8, 0, 38, 26);
  *(uint32_t*)0x2000000003f0 = 0;
  *(uint32_t*)0x2000000003f4 = 4;
  *(uint64_t*)0x2000000003f8 = 8;
  *(uint64_t*)0x200000000400 = 0x830d;
  *(uint64_t*)0x200000000408 = 0;
  *(uint64_t*)0x200000000410 = 2;
  *(uint32_t*)0x200000000418 = 0xfffffffe;
  *(uint32_t*)0x20000000041c = 0;
  *(uint64_t*)0x200000000420 = 0;
  *(uint32_t*)0x200000000428 = 0;
  *(uint16_t*)0x20000000042c = 0;
  *(uint16_t*)0x20000000042e = 0;
  *(uint32_t*)0x200000000430 = 0;
  *(uint32_t*)0x200000000434 = 0;
  *(uint64_t*)0x200000000438 = 0;
  syscall(__NR_perf_event_open, /*attr=*/0x2000000003c0ul, /*pid=*/0,
          /*cpu=*/(intptr_t)-1, /*group=*/(intptr_t)-1, /*flags=*/0ul);
  //  perf_event_open arguments: [
  //    attr: ptr[in, perf_event_attr] {
  //      perf_event_attr {
  //        type: perf_event_type = 0x2 (4 bytes)
  //        size: len = 0x80 (4 bytes)
  //        config0: int8 = 0x48 (1 bytes)
  //        config1: int8 = 0x1 (1 bytes)
  //        config2: int8 = 0x0 (1 bytes)
  //        config3: int8 = 0x0 (1 bytes)
  //        config4: const = 0x0 (4 bytes)
  //        sample_freq: int64 = 0x9 (8 bytes)
  //        sample_type: perf_sample_type = 0x20 (8 bytes)
  //        read_format: perf_read_format = 0xe (8 bytes)
  //        disabled: int64 = 0x0 (0 bytes)
  //        inherit: int64 = 0x0 (0 bytes)
  //        pinned: int64 = 0x0 (0 bytes)
  //        exclusive: int64 = 0x0 (0 bytes)
  //        exclude_user: int64 = 0x0 (0 bytes)
  //        exclude_kernel: int64 = 0x0 (0 bytes)
  //        exclude_hv: int64 = 0x0 (0 bytes)
  //        exclude_idle: int64 = 0x0 (0 bytes)
  //        mmap: int64 = 0x0 (0 bytes)
  //        comm: int64 = 0x0 (0 bytes)
  //        freq: int64 = 0x0 (0 bytes)
  //        inherit_stat: int64 = 0x0 (0 bytes)
  //        enable_on_exec: int64 = 0x0 (0 bytes)
  //        task: int64 = 0x0 (0 bytes)
  //        watermark: int64 = 0x0 (0 bytes)
  //        precise_ip: int64 = 0x0 (0 bytes)
  //        mmap_data: int64 = 0x0 (0 bytes)
  //        sample_id_all: int64 = 0x0 (0 bytes)
  //        exclude_host: int64 = 0x0 (0 bytes)
  //        exclude_guest: int64 = 0x0 (0 bytes)
  //        exclude_callchain_kernel: int64 = 0x0 (0 bytes)
  //        exclude_callchain_user: int64 = 0x0 (0 bytes)
  //        mmap2: int64 = 0x0 (0 bytes)
  //        comm_exec: int64 = 0x0 (0 bytes)
  //        use_clockid: int64 = 0x0 (0 bytes)
  //        context_switch: int64 = 0x0 (0 bytes)
  //        write_backward: int64 = 0x0 (0 bytes)
  //        namespaces: int64 = 0x0 (0 bytes)
  //        ksymbol: int64 = 0x0 (0 bytes)
  //        bpf_event: int64 = 0x0 (0 bytes)
  //        aux_output: int64 = 0x0 (0 bytes)
  //        cgroup: int64 = 0x0 (0 bytes)
  //        text_poke: int64 = 0x0 (0 bytes)
  //        build_id: int64 = 0x0 (0 bytes)
  //        inherit_thread: int64 = 0x0 (0 bytes)
  //        remove_on_exec: int64 = 0x0 (0 bytes)
  //        sigtrap: int64 = 0x0 (0 bytes)
  //        __reserved_1: const = 0x0 (8 bytes)
  //        wakeup_events: int32 = 0x0 (4 bytes)
  //        bp_type: perf_bp_type = 0x0 (4 bytes)
  //        bp_config: union perf_bp_config {
  //          perf_config_ext: perf_config_ext {
  //            config1: int64 = 0x2 (8 bytes)
  //            config2: int64 = 0x1946 (8 bytes)
  //          }
  //        }
  //        branch_sample_type: perf_branch_sample_type = 0x0 (8 bytes)
  //        sample_regs_user: int64 = 0x0 (8 bytes)
  //        sample_stack_user: int32 = 0x0 (4 bytes)
  //        clockid: clock_type = 0x8 (4 bytes)
  //        sample_regs_intr: int64 = 0x7fff (8 bytes)
  //        aux_watermark: int32 = 0x7fffffff (4 bytes)
  //        sample_max_stack: int16 = 0x0 (2 bytes)
  //        __reserved_2: const = 0x0 (2 bytes)
  //        aux_sample_size: int32 = 0x0 (4 bytes)
  //        __reserved_3: const = 0x0 (4 bytes)
  //        sig_data: int64 = 0x0 (8 bytes)
  //      }
  //    }
  //    pid: pid (resource)
  //    cpu: intptr = 0xffffffffffffffff (8 bytes)
  //    group: fd_perf (resource)
  //    flags: perf_flags = 0xa (8 bytes)
  //  ]
  //  returns fd_perf
  *(uint32_t*)0x200000000180 = 2;
  *(uint32_t*)0x200000000184 = 0x80;
  *(uint8_t*)0x200000000188 = 0x48;
  *(uint8_t*)0x200000000189 = 1;
  *(uint8_t*)0x20000000018a = 0;
  *(uint8_t*)0x20000000018b = 0;
  *(uint32_t*)0x20000000018c = 0;
  *(uint64_t*)0x200000000190 = 9;
  *(uint64_t*)0x200000000198 = 0x20;
  *(uint64_t*)0x2000000001a0 = 0xe;
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 0, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 1, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 2, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 3, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 4, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 5, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 6, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 7, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 8, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 9, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 10, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 11, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 12, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 13, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 14, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 15, 2);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 17, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 18, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 19, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 20, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 21, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 22, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 23, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 24, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 25, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 26, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 27, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 28, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 29, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 30, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 31, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 32, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 33, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 34, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 35, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 36, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 37, 1);
  STORE_BY_BITMASK(uint64_t, , 0x2000000001a8, 0, 38, 26);
  *(uint32_t*)0x2000000001b0 = 0;
  *(uint32_t*)0x2000000001b4 = 0;
  *(uint64_t*)0x2000000001b8 = 2;
  *(uint64_t*)0x2000000001c0 = 0x1946;
  *(uint64_t*)0x2000000001c8 = 0;
  *(uint64_t*)0x2000000001d0 = 0;
  *(uint32_t*)0x2000000001d8 = 0;
  *(uint32_t*)0x2000000001dc = 8;
  *(uint64_t*)0x2000000001e0 = 0x7fff;
  *(uint32_t*)0x2000000001e8 = 0x7fffffff;
  *(uint16_t*)0x2000000001ec = 0;
  *(uint16_t*)0x2000000001ee = 0;
  *(uint32_t*)0x2000000001f0 = 0;
  *(uint32_t*)0x2000000001f4 = 0;
  *(uint64_t*)0x2000000001f8 = 0;
  syscall(__NR_perf_event_open, /*attr=*/0x200000000180ul, /*pid=*/0,
          /*cpu=*/(intptr_t)-1, /*group=*/(intptr_t)-1,
          /*flags=PERF_FLAG_FD_CLOEXEC|PERF_FLAG_FD_OUTPUT*/ 0xaul);
  //  bpf$PROG_LOAD arguments: [
  //    cmd: const = 0x5 (8 bytes)
  //    arg: ptr[in, bpf_prog_t[flags[bpf_prog_type, int32],
  //    bpf_prog_attach_types, bpf_btf_id[opt], fd_bpf_prog[opt]]] {
  //      bpf_prog_t[flags[bpf_prog_type, int32], bpf_prog_attach_types,
  //      bpf_btf_id[opt], fd_bpf_prog[opt]] {
  //        type: bpf_prog_type = 0xf (4 bytes)
  //        ninsn: bytesize8 = 0xc (4 bytes)
  //        insns: ptr[inout, array[ANYUNION]] {
  //          array[ANYUNION] {
  //            union ANYUNION {
  //              ANYBLOB: buffer: {18 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  //              00 18 00 00 00} (length 0x14)
  //            }
  //            union ANYUNION {
  //              ANYRES32: ANYRES32 (resource)
  //            }
  //            union ANYUNION {
  //              ANYBLOB: buffer: {00 00 00 00 00 00 00 00 b7 08 00 00 00 00 00
  //              00 7b 8a f8 ff 00 00 00 00 bf a2 00 00 00 00 00 00 07 02 00 00
  //              f8 ff ff ff b7 03 00 00 08 00 00 00 b7 04 00 00 03 00 00 00 85
  //              00 00 00 43 00 00 00 95} (length 0x41)
  //            }
  //          }
  //        }
  //        license: nil
  //        loglev: int32 = 0x0 (4 bytes)
  //        logsize: len = 0x0 (4 bytes)
  //        log: nil
  //        kern_version: bpf_kern_version = 0x0 (4 bytes)
  //        flags: bpf_prog_load_flags = 0x8 (4 bytes)
  //        prog_name: buffer: {00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00}
  //        (length 0x10) prog_ifindex: ifindex (resource) expected_attach_type:
  //        union bpf_prog_attach_types {
  //          fallback: bpf_attach_types = 0x0 (4 bytes)
  //        }
  //        btf_fd: fd_btf (resource)
  //        func_info_rec_size: const = 0x0 (4 bytes)
  //        func_info: nil
  //        func_info_cnt: len = 0x0 (4 bytes)
  //        line_info_rec_size: const = 0x0 (4 bytes)
  //        line_info: nil
  //        line_info_cnt: len = 0x0 (4 bytes)
  //        attach_btf_id: bpf_btf_id (resource)
  //        attach_prog_fd: fd_bpf_prog (resource)
  //        core_relo_cnt: len = 0x0 (4 bytes)
  //        fd_array: nil
  //        core_relos: nil
  //        core_relo_rec_size: const = 0x0 (4 bytes)
  //        log_true_size: int32 = 0x0 (4 bytes)
  //        prog_token_fd: union _bpf_prog_t[flags[bpf_prog_type, int32],
  //        bpf_prog_attach_types, bpf_btf_id[opt],
  //        fd_bpf_prog[opt]]_prog_token_fd_wrapper {
  //          void: buffer: {} (length 0x0)
  //        }
  //        pad: union _bpf_prog_t[flags[bpf_prog_type, int32],
  //        bpf_prog_attach_types, bpf_btf_id[opt],
  //        fd_bpf_prog[opt]]_pad_wrapper {
  //          value: const = 0x0 (4 bytes)
  //        }
  //      }
  //    }
  //    size: len = 0x94 (8 bytes)
  //  ]
  //  returns fd_bpf_prog
  *(uint32_t*)0x200000000400 = 0xf;
  *(uint32_t*)0x200000000404 = 0xc;
  *(uint64_t*)0x200000000408 = 0x200000000240;
  memcpy((void*)0x200000000240,
         "\x18\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x18"
         "\x00\x00\x00",
         20);
  *(uint32_t*)0x200000000254 = -1;
  memcpy((void*)0x200000000258,
         "\x00\x00\x00\x00\x00\x00\x00\x00\xb7\x08\x00\x00\x00\x00\x00\x00\x7b"
         "\x8a\xf8\xff\x00\x00\x00\x00\xbf\xa2\x00\x00\x00\x00\x00\x00\x07\x02"
         "\x00\x00\xf8\xff\xff\xff\xb7\x03\x00\x00\x08\x00\x00\x00\xb7\x04\x00"
         "\x00\x03\x00\x00\x00\x85\x00\x00\x00\x43\x00\x00\x00\x95",
         65);
  *(uint64_t*)0x200000000410 = 0;
  *(uint32_t*)0x200000000418 = 0;
  *(uint32_t*)0x20000000041c = 0;
  *(uint64_t*)0x200000000420 = 0;
  *(uint32_t*)0x200000000428 = 0;
  *(uint32_t*)0x20000000042c = 8;
  memset((void*)0x200000000430, 0, 16);
  *(uint32_t*)0x200000000440 = 0;
  *(uint32_t*)0x200000000444 = 0;
  *(uint32_t*)0x200000000448 = -1;
  *(uint32_t*)0x20000000044c = 0;
  *(uint64_t*)0x200000000450 = 0;
  *(uint32_t*)0x200000000458 = 0;
  *(uint32_t*)0x20000000045c = 0;
  *(uint64_t*)0x200000000460 = 0;
  *(uint32_t*)0x200000000468 = 0;
  *(uint32_t*)0x20000000046c = 0;
  *(uint32_t*)0x200000000470 = 0;
  *(uint32_t*)0x200000000474 = 0;
  *(uint64_t*)0x200000000478 = 0;
  *(uint64_t*)0x200000000480 = 0;
  *(uint32_t*)0x200000000488 = 0;
  *(uint32_t*)0x20000000048c = 0;
  *(uint32_t*)0x200000000490 = 0;
  syscall(__NR_bpf, /*cmd=*/5ul, /*arg=*/0x200000000400ul, /*size=*/0x94ul);
  //  bpf$PROG_LOAD arguments: [
  //    cmd: const = 0x5 (8 bytes)
  //    arg: ptr[in, bpf_prog_t[flags[bpf_prog_type, int32],
  //    bpf_prog_attach_types, bpf_btf_id[opt], fd_bpf_prog[opt]]] {
  //      bpf_prog_t[flags[bpf_prog_type, int32], bpf_prog_attach_types,
  //      bpf_btf_id[opt], fd_bpf_prog[opt]] {
  //        type: bpf_prog_type = 0x11 (4 bytes)
  //        ninsn: bytesize8 = 0xc (4 bytes)
  //        insns: ptr[inout, array[ANYUNION]] {
  //          array[ANYUNION] {
  //          }
  //        }
  //        license: ptr[in, buffer] {
  //          buffer: {47 50 4c 00} (length 0x4)
  //        }
  //        loglev: int32 = 0x0 (4 bytes)
  //        logsize: len = 0x0 (4 bytes)
  //        log: nil
  //        kern_version: bpf_kern_version = 0x0 (4 bytes)
  //        flags: bpf_prog_load_flags = 0x68 (4 bytes)
  //        prog_name: buffer: {00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00}
  //        (length 0x10) prog_ifindex: ifindex (resource) expected_attach_type:
  //        union bpf_prog_attach_types {
  //          fallback: bpf_attach_types = 0x0 (4 bytes)
  //        }
  //        btf_fd: fd_btf (resource)
  //        func_info_rec_size: const = 0x0 (4 bytes)
  //        func_info: nil
  //        func_info_cnt: len = 0x0 (4 bytes)
  //        line_info_rec_size: const = 0x0 (4 bytes)
  //        line_info: nil
  //        line_info_cnt: len = 0x0 (4 bytes)
  //        attach_btf_id: bpf_btf_id (resource)
  //        attach_prog_fd: fd_bpf_prog (resource)
  //        core_relo_cnt: len = 0x0 (4 bytes)
  //        fd_array: nil
  //        core_relos: nil
  //        core_relo_rec_size: const = 0x0 (4 bytes)
  //        log_true_size: int32 = 0x0 (4 bytes)
  //        prog_token_fd: union _bpf_prog_t[flags[bpf_prog_type, int32],
  //        bpf_prog_attach_types, bpf_btf_id[opt],
  //        fd_bpf_prog[opt]]_prog_token_fd_wrapper {
  //          void: buffer: {} (length 0x0)
  //        }
  //        pad: union _bpf_prog_t[flags[bpf_prog_type, int32],
  //        bpf_prog_attach_types, bpf_btf_id[opt],
  //        fd_bpf_prog[opt]]_pad_wrapper {
  //          value: const = 0x0 (4 bytes)
  //        }
  //      }
  //    }
  //    size: len = 0x94 (8 bytes)
  //  ]
  //  returns fd_bpf_prog
  *(uint32_t*)0x2000000000c0 = 0x11;
  *(uint32_t*)0x2000000000c4 = 0xc;
  *(uint64_t*)0x2000000000c8 = 0x200000000240;
  *(uint64_t*)0x2000000000d0 = 0x2000000003c0;
  memcpy((void*)0x2000000003c0, "GPL\000", 4);
  *(uint32_t*)0x2000000000d8 = 0;
  *(uint32_t*)0x2000000000dc = 0;
  *(uint64_t*)0x2000000000e0 = 0;
  *(uint32_t*)0x2000000000e8 = 0;
  *(uint32_t*)0x2000000000ec = 0x68;
  memset((void*)0x2000000000f0, 0, 16);
  *(uint32_t*)0x200000000100 = 0;
  *(uint32_t*)0x200000000104 = 0;
  *(uint32_t*)0x200000000108 = -1;
  *(uint32_t*)0x20000000010c = 0;
  *(uint64_t*)0x200000000110 = 0;
  *(uint32_t*)0x200000000118 = 0;
  *(uint32_t*)0x20000000011c = 0;
  *(uint64_t*)0x200000000120 = 0;
  *(uint32_t*)0x200000000128 = 0;
  *(uint32_t*)0x20000000012c = 0;
  *(uint32_t*)0x200000000130 = 0;
  *(uint32_t*)0x200000000134 = 0;
  *(uint64_t*)0x200000000138 = 0;
  *(uint64_t*)0x200000000140 = 0;
  *(uint32_t*)0x200000000148 = 0;
  *(uint32_t*)0x20000000014c = 0;
  *(uint32_t*)0x200000000150 = 0;
  res =
      syscall(__NR_bpf, /*cmd=*/5ul, /*arg=*/0x2000000000c0ul, /*size=*/0x94ul);
  if (res != -1)
    r[0] = res;
  //  bpf$BPF_RAW_TRACEPOINT_OPEN arguments: [
  //    cmd: const = 0x11 (8 bytes)
  //    arg: ptr[in, bpf_raw_tracepoint] {
  //      bpf_raw_tracepoint {
  //        name: ptr[in, buffer] {
  //          buffer: {6b 66 72 65 65 00} (length 0x6)
  //        }
  //        prog_fd: fd_bpf_prog_raw_tracepoint (resource)
  //        pad: const = 0x0 (4 bytes)
  //        cookie: int64 = 0x8000000008 (8 bytes)
  //      }
  //    }
  //    size: len = 0x18 (8 bytes)
  //  ]
  //  returns fd_perf_base
  *(uint64_t*)0x200000000340 = 0x200000000300;
  memcpy((void*)0x200000000300, "kfree\000", 6);
  *(uint32_t*)0x200000000348 = r[0];
  *(uint32_t*)0x20000000034c = 0;
  *(uint64_t*)0x200000000350 = 0x8000000008;
  syscall(__NR_bpf, /*cmd=*/0x11ul, /*arg=*/0x200000000340ul, /*size=*/0x18ul);
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  for (procid = 0; procid < 5; procid++) {
    if (fork() == 0) {
      loop();
    }
  }
  sleep(1000000);
  return 0;
}
