// https://syzkaller.appspot.com/bug?id=e73f7d3fe11e7b14c41c9dcf786c3fa21ff0b0ec
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#ifndef __NR_bpf
#define __NR_bpf 321
#endif

static __thread int clone_ongoing;
static __thread int skip_segv;
static __thread jmp_buf segv_env;

static void segv_handler(int sig, siginfo_t* info, void* ctx)
{
  if (__atomic_load_n(&clone_ongoing, __ATOMIC_RELAXED) != 0) {
    exit(sig);
  }
  uintptr_t addr = (uintptr_t)info->si_addr;
  const uintptr_t prog_start = 1 << 20;
  const uintptr_t prog_end = 100 << 20;
  int skip = __atomic_load_n(&skip_segv, __ATOMIC_RELAXED) != 0;
  int valid = addr < prog_start || addr > prog_end;
  if (skip && valid) {
    _longjmp(segv_env, 1);
  }
  exit(sig);
}

static void install_segv_handler(void)
{
  struct sigaction sa;
  memset(&sa, 0, sizeof(sa));
  sa.sa_handler = SIG_IGN;
  syscall(SYS_rt_sigaction, 0x20, &sa, NULL, 8);
  syscall(SYS_rt_sigaction, 0x21, &sa, NULL, 8);
  memset(&sa, 0, sizeof(sa));
  sa.sa_sigaction = segv_handler;
  sa.sa_flags = SA_NODEFER | SA_SIGINFO;
  sigaction(SIGSEGV, &sa, NULL);
  sigaction(SIGBUS, &sa, NULL);
}

#define NONFAILING(...)                                                        \
  ({                                                                           \
    int ok = 1;                                                                \
    __atomic_fetch_add(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
    if (_setjmp(segv_env) == 0) {                                              \
      __VA_ARGS__;                                                             \
    } else                                                                     \
      ok = 0;                                                                  \
    __atomic_fetch_sub(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
    ok;                                                                        \
  })

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static void use_temporary_dir(void)
{
  char tmpdir_template[] = "./syzkaller.XXXXXX";
  char* tmpdir = mkdtemp(tmpdir_template);
  if (!tmpdir)
    exit(1);
  if (chmod(tmpdir, 0777))
    exit(1);
  if (chdir(tmpdir))
    exit(1);
}

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

#define FS_IOC_SETFLAGS _IOW('f', 2, long)
static void remove_dir(const char* dir)
{
  int iter = 0;
  DIR* dp = 0;
  const int umount_flags = MNT_FORCE | UMOUNT_NOFOLLOW;

retry:
  while (umount2(dir, umount_flags) == 0) {
  }
  dp = opendir(dir);
  if (dp == NULL) {
    if (errno == EMFILE) {
      exit(1);
    }
    exit(1);
  }
  struct dirent* ep = 0;
  while ((ep = readdir(dp))) {
    if (strcmp(ep->d_name, ".") == 0 || strcmp(ep->d_name, "..") == 0)
      continue;
    char filename[FILENAME_MAX];
    snprintf(filename, sizeof(filename), "%s/%s", dir, ep->d_name);
    while (umount2(filename, umount_flags) == 0) {
    }
    struct stat st;
    if (lstat(filename, &st))
      exit(1);
    if (S_ISDIR(st.st_mode)) {
      remove_dir(filename);
      continue;
    }
    int i;
    for (i = 0;; i++) {
      if (unlink(filename) == 0)
        break;
      if (errno == EPERM) {
        int fd = open(filename, O_RDONLY);
        if (fd != -1) {
          long flags = 0;
          if (ioctl(fd, FS_IOC_SETFLAGS, &flags) == 0) {
          }
          close(fd);
          continue;
        }
      }
      if (errno == EROFS) {
        break;
      }
      if (errno != EBUSY || i > 100)
        exit(1);
      if (umount2(filename, umount_flags))
        exit(1);
    }
  }
  closedir(dp);
  for (int i = 0;; i++) {
    if (rmdir(dir) == 0)
      break;
    if (i < 100) {
      if (errno == EPERM) {
        int fd = open(dir, O_RDONLY);
        if (fd != -1) {
          long flags = 0;
          if (ioctl(fd, FS_IOC_SETFLAGS, &flags) == 0) {
          }
          close(fd);
          continue;
        }
      }
      if (errno == EROFS) {
        break;
      }
      if (errno == EBUSY) {
        if (umount2(dir, umount_flags))
          exit(1);
        continue;
      }
      if (errno == ENOTEMPTY) {
        if (iter < 100) {
          iter++;
          goto retry;
        }
      }
    }
    exit(1);
  }
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
  if (symlink("/dev/binderfs", "./binderfs")) {
  }
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    char cwdbuf[32];
    sprintf(cwdbuf, "./%d", iter);
    if (mkdir(cwdbuf, 0777))
      exit(1);
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      if (chdir(cwdbuf))
        exit(1);
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      sleep_ms(10);
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
    remove_dir(cwdbuf);
  }
}

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  //  bpf$MAP_CREATE arguments: [
  //    cmd: const = 0x0 (8 bytes)
  //    arg: ptr[inout, array[ANYUNION]] {
  //      array[ANYUNION] {
  //        union ANYUNION {
  //          ANYBLOB: buffer: {07 00 00 00 04 00 00 00 08 02 00 00 21} (length
  //          0xd)
  //        }
  //      }
  //    }
  //    size: len = 0x50 (8 bytes)
  //  ]
  //  returns fd_bpf_map
  NONFAILING(memcpy((void*)0x200000000280,
                    "\x07\x00\x00\x00\x04\x00\x00\x00\x08\x02\x00\x00\x21",
                    13));
  res =
      syscall(__NR_bpf, /*cmd=*/0ul, /*arg=*/0x200000000280ul, /*size=*/0x50ul);
  if (res != -1)
    r[0] = res;
  //  bpf$PROG_LOAD arguments: [
  //    cmd: const = 0x5 (8 bytes)
  //    arg: ptr[in, bpf_prog_t[flags[bpf_prog_type, int32],
  //    bpf_prog_attach_types, bpf_btf_id[opt], fd_bpf_prog[opt]]] {
  //      bpf_prog_t[flags[bpf_prog_type, int32], bpf_prog_attach_types,
  //      bpf_btf_id[opt], fd_bpf_prog[opt]] {
  //        type: bpf_prog_type = 0x11 (4 bytes)
  //        ninsn: bytesize8 = 0x8 (4 bytes)
  //        insns: ptr[inout, array[ANYUNION]] {
  //          array[ANYUNION] {
  //            union ANYUNION {
  //              ANYBLOB: buffer: {18 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  //              00 18 12 00 00} (length 0x14)
  //            }
  //            union ANYUNION {
  //              ANYRES32: ANYRES32 (resource)
  //            }
  //            union ANYUNION {
  //              ANYBLOB: buffer: {00 00 00 00 00 00 00 00 b7 03 00 00 00 04 00
  //              00 85 00 00 00 1b 00 00 00 b7 00 00 00 00 00 00 00 95} (length
  //              0x21)
  //            }
  //          }
  //        }
  //        license: ptr[in, buffer] {
  //          buffer: {47 50 4c 00} (length 0x4)
  //        }
  //        loglev: int32 = 0x0 (4 bytes)
  //        logsize: len = 0x0 (4 bytes)
  //        log: nil
  //        kern_version: bpf_kern_version = 0x41100 (4 bytes)
  //        flags: bpf_prog_load_flags = 0x0 (4 bytes)
  //        prog_name: buffer: {00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00}
  //        (length 0x10) prog_ifindex: ifindex (resource) expected_attach_type:
  //        union bpf_prog_attach_types {
  //          fallback: bpf_attach_types = 0x2c (4 bytes)
  //        }
  //        btf_fd: fd_btf (resource)
  //        func_info_rec_size: const = 0x0 (4 bytes)
  //        func_info: nil
  //        func_info_cnt: len = 0x0 (4 bytes)
  //        line_info_rec_size: const = 0x0 (4 bytes)
  //        line_info: nil
  //        line_info_cnt: len = 0x0 (4 bytes)
  //        attach_btf_id: bpf_btf_id (resource)
  //        attach_prog_fd: fd_bpf_prog (resource)
  //        core_relo_cnt: len = 0x0 (4 bytes)
  //        fd_array: nil
  //        core_relos: nil
  //        core_relo_rec_size: const = 0x0 (4 bytes)
  //        log_true_size: int32 = 0x0 (4 bytes)
  //        prog_token_fd: union _bpf_prog_t[flags[bpf_prog_type, int32],
  //        bpf_prog_attach_types, bpf_btf_id[opt],
  //        fd_bpf_prog[opt]]_prog_token_fd_wrapper {
  //          void: buffer: {} (length 0x0)
  //        }
  //        pad: union _bpf_prog_t[flags[bpf_prog_type, int32],
  //        bpf_prog_attach_types, bpf_btf_id[opt],
  //        fd_bpf_prog[opt]]_pad_wrapper {
  //          value: const = 0x0 (4 bytes)
  //        }
  //      }
  //    }
  //    size: len = 0x94 (8 bytes)
  //  ]
  //  returns fd_bpf_prog
  NONFAILING(*(uint32_t*)0x200000000680 = 0x11);
  NONFAILING(*(uint32_t*)0x200000000684 = 8);
  NONFAILING(*(uint64_t*)0x200000000688 = 0x200000000740);
  NONFAILING(memcpy((void*)0x200000000740,
                    "\x18\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                    "\x00\x00\x18\x12\x00\x00",
                    20));
  NONFAILING(*(uint32_t*)0x200000000754 = r[0]);
  NONFAILING(memcpy(
      (void*)0x200000000758,
      "\x00\x00\x00\x00\x00\x00\x00\x00\xb7\x03\x00\x00\x00\x04\x00\x00\x85\x00"
      "\x00\x00\x1b\x00\x00\x00\xb7\x00\x00\x00\x00\x00\x00\x00\x95",
      33));
  NONFAILING(*(uint64_t*)0x200000000690 = 0x2000000000c0);
  NONFAILING(memcpy((void*)0x2000000000c0, "GPL\000", 4));
  NONFAILING(*(uint32_t*)0x200000000698 = 0);
  NONFAILING(*(uint32_t*)0x20000000069c = 0);
  NONFAILING(*(uint64_t*)0x2000000006a0 = 0);
  NONFAILING(*(uint32_t*)0x2000000006a8 = 0x41100);
  NONFAILING(*(uint32_t*)0x2000000006ac = 0);
  NONFAILING(memset((void*)0x2000000006b0, 0, 16));
  NONFAILING(*(uint32_t*)0x2000000006c0 = 0);
  NONFAILING(*(uint32_t*)0x2000000006c4 = 0x2c);
  NONFAILING(*(uint32_t*)0x2000000006c8 = 0);
  NONFAILING(*(uint32_t*)0x2000000006cc = 0);
  NONFAILING(*(uint64_t*)0x2000000006d0 = 0);
  NONFAILING(*(uint32_t*)0x2000000006d8 = 0);
  NONFAILING(*(uint32_t*)0x2000000006dc = 0);
  NONFAILING(*(uint64_t*)0x2000000006e0 = 0);
  NONFAILING(*(uint32_t*)0x2000000006e8 = 0);
  NONFAILING(*(uint32_t*)0x2000000006ec = 0);
  NONFAILING(*(uint32_t*)0x2000000006f0 = 0);
  NONFAILING(*(uint32_t*)0x2000000006f4 = 0);
  NONFAILING(*(uint64_t*)0x2000000006f8 = 0);
  NONFAILING(*(uint64_t*)0x200000000700 = 0);
  NONFAILING(*(uint32_t*)0x200000000708 = 0);
  NONFAILING(*(uint32_t*)0x20000000070c = 0);
  NONFAILING(*(uint32_t*)0x200000000710 = 0);
  res =
      syscall(__NR_bpf, /*cmd=*/5ul, /*arg=*/0x200000000680ul, /*size=*/0x94ul);
  if (res != -1)
    r[1] = res;
  //  bpf$BPF_RAW_TRACEPOINT_OPEN arguments: [
  //    cmd: const = 0x11 (8 bytes)
  //    arg: ptr[in, bpf_raw_tracepoint] {
  //      bpf_raw_tracepoint {
  //        name: ptr[in, buffer] {
  //          buffer: {6b 6d 65 6d 5f 63 61 63 68 65 5f 66 72 65 65 00} (length
  //          0x10)
  //        }
  //        prog_fd: fd_bpf_prog_raw_tracepoint (resource)
  //        pad: const = 0x0 (4 bytes)
  //        cookie: int64 = 0x0 (8 bytes)
  //      }
  //    }
  //    size: len = 0x18 (8 bytes)
  //  ]
  //  returns fd_perf_base
  NONFAILING(*(uint64_t*)0x200000000bc0 = 0x200000000040);
  NONFAILING(memcpy((void*)0x200000000040, "kmem_cache_free\000", 16));
  NONFAILING(*(uint32_t*)0x200000000bc8 = r[1]);
  NONFAILING(*(uint32_t*)0x200000000bcc = 0);
  NONFAILING(*(uint64_t*)0x200000000bd0 = 0);
  syscall(__NR_bpf, /*cmd=*/0x11ul, /*arg=*/0x200000000bc0ul, /*size=*/0x18ul);
  for (int i = 0; i < 64; i++) {
    syscall(__NR_bpf, /*cmd=*/0x11ul, /*arg=*/0x200000000bc0ul,
            /*size=*/0x18ul);
  }
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  install_segv_handler();
  use_temporary_dir();
  loop();
  return 0;
}
